name = "Mojo-IOLoop-ReadWriteProcess"
badges = ["codecov", "github-actions/linux"]
module_maker="ModuleBuild"

[build]
build_class = "builder::custom"

[Metadata.resources]
repository = "https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess"

[unsupported]
os = [
    "MSWin32",
    "cygwin",
]

[tap_harness_args]
merge = 1
