name: Unit and integration tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        perl:
          - '5.20'
          - '5.26'
          - '5.30'
          - '5.34'
          - '5.36'
          - '5.38'
          - '5.40'
          - latest
        include:
          - os: macos-latest
            perl: '5.26'
          - os: macos-latest
            perl: latest
    name: 🐪 Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: shogo82148/actions-setup-perl@a198315ec4e9244f206879ea7b63078003aec8a6  # v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: perl -V
        run: perl -V
      - name: Set up perl
        run: |
          if [ "${{ matrix.perl }}" = "latest" ] && [ "${{ matrix.os }}" != "macos-latest" ]; then
            cpanm --with-feature=ci --installdeps --notest .
          else
            cpanm --installdeps --notest .
          fi
      - name: Run tests
        if: matrix.perl != 'latest' || matrix.os == 'macos-latest'
        run: |
          TEST_SHARED=1 TEST_SUBREAPER=1 prove -l t
      - name: Run tests with coverage and retry
        if: matrix.perl == 'latest' && matrix.os != 'macos-latest'
        run: |
          # t/01_run.t can segfault, retrying multiple times
          # See https://progress.opensuse.org/issues/180026
          curl -O https://raw.githubusercontent.com/okurz/retry/refs/heads/main/retry
          chmod +x retry
          ./retry -r 7 env TEST_SHARED=1 TEST_SUBREAPER=1 PERL5OPT="-MDevel::Cover=-coverage,statement" prove -l t
          cover -report codecovbash
      - name: Upload coverage to ☂️ Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        if: matrix.perl == 'latest' && matrix.os != 'macos-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
